/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LocaleSignupRouteImport } from './routes/$locale.signup'
import { Route as LocaleMotDePasseOublieRouteImport } from './routes/$locale.mot-de-passe-oublie'
import { Route as LocaleLoginProRouteImport } from './routes/$locale.login-pro'
import { Route as LocaleLoginAdminRouteImport } from './routes/$locale.login-admin'
import { Route as LocaleLoginRouteImport } from './routes/$locale.login'
import { Route as LocaleInscriptionRouteImport } from './routes/$locale.inscription'
import { Route as LocaleEspaceProRouteImport } from './routes/$locale.espace-pro'
import { Route as LocaleEspacePatientRouteImport } from './routes/$locale.espace-patient'
import { Route as LocaleAdminRouteImport } from './routes/$locale.admin'
import { Route as LocaleEspaceProIndexRouteImport } from './routes/$locale.espace-pro.index'
import { Route as LocaleEspacePatientIndexRouteImport } from './routes/$locale.espace-patient.index'
import { Route as LocaleAdminIndexRouteImport } from './routes/$locale.admin.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LocaleEspaceProProfilPublicRouteImport } from './routes/$locale.espace-pro.profil-public'
import { Route as LocaleEspaceProPatientsRouteImport } from './routes/$locale.espace-pro.patients'
import { Route as LocaleEspaceProDossiersRouteImport } from './routes/$locale.espace-pro.dossiers'
import { Route as LocaleEspaceProAbonnementRouteImport } from './routes/$locale.espace-pro.abonnement'
import { Route as LocaleEspacePatientSecuriteRouteImport } from './routes/$locale.espace-patient.securite'
import { Route as LocaleEspacePatientProfilRouteImport } from './routes/$locale.espace-patient.profil'
import { Route as LocaleEspacePatientDocumentsRouteImport } from './routes/$locale.espace-patient.documents'
import { Route as LocaleAdminVerificationsRouteImport } from './routes/$locale.admin.verifications'
import { Route as LocaleAdminAuditRouteImport } from './routes/$locale.admin.audit'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleSignupRoute = LocaleSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMotDePasseOublieRoute = LocaleMotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginProRoute = LocaleLoginProRouteImport.update({
  id: '/login-pro',
  path: '/login-pro',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginAdminRoute = LocaleLoginAdminRouteImport.update({
  id: '/login-admin',
  path: '/login-admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleInscriptionRoute = LocaleInscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEspaceProRoute = LocaleEspaceProRouteImport.update({
  id: '/espace-pro',
  path: '/espace-pro',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEspacePatientRoute = LocaleEspacePatientRouteImport.update({
  id: '/espace-patient',
  path: '/espace-patient',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEspaceProIndexRoute = LocaleEspaceProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleEspaceProRoute,
} as any)
const LocaleEspacePatientIndexRoute =
  LocaleEspacePatientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleEspacePatientRoute,
  } as any)
const LocaleAdminIndexRoute = LocaleAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleEspaceProProfilPublicRoute =
  LocaleEspaceProProfilPublicRouteImport.update({
    id: '/profil-public',
    path: '/profil-public',
    getParentRoute: () => LocaleEspaceProRoute,
  } as any)
const LocaleEspaceProPatientsRoute = LocaleEspaceProPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => LocaleEspaceProRoute,
} as any)
const LocaleEspaceProDossiersRoute = LocaleEspaceProDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => LocaleEspaceProRoute,
} as any)
const LocaleEspaceProAbonnementRoute =
  LocaleEspaceProAbonnementRouteImport.update({
    id: '/abonnement',
    path: '/abonnement',
    getParentRoute: () => LocaleEspaceProRoute,
  } as any)
const LocaleEspacePatientSecuriteRoute =
  LocaleEspacePatientSecuriteRouteImport.update({
    id: '/securite',
    path: '/securite',
    getParentRoute: () => LocaleEspacePatientRoute,
  } as any)
const LocaleEspacePatientProfilRoute =
  LocaleEspacePatientProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => LocaleEspacePatientRoute,
  } as any)
const LocaleEspacePatientDocumentsRoute =
  LocaleEspacePatientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => LocaleEspacePatientRoute,
  } as any)
const LocaleAdminVerificationsRoute =
  LocaleAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => LocaleAdminRoute,
  } as any)
const LocaleAdminAuditRoute = LocaleAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LocaleAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/mcp': typeof McpRoute
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/espace-patient': typeof LocaleEspacePatientRouteWithChildren
  '/$locale/espace-pro': typeof LocaleEspaceProRouteWithChildren
  '/$locale/inscription': typeof LocaleInscriptionRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/login-admin': typeof LocaleLoginAdminRoute
  '/$locale/login-pro': typeof LocaleLoginProRoute
  '/$locale/mot-de-passe-oublie': typeof LocaleMotDePasseOublieRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/audit': typeof LocaleAdminAuditRoute
  '/$locale/admin/verifications': typeof LocaleAdminVerificationsRoute
  '/$locale/espace-patient/documents': typeof LocaleEspacePatientDocumentsRoute
  '/$locale/espace-patient/profil': typeof LocaleEspacePatientProfilRoute
  '/$locale/espace-patient/securite': typeof LocaleEspacePatientSecuriteRoute
  '/$locale/espace-pro/abonnement': typeof LocaleEspaceProAbonnementRoute
  '/$locale/espace-pro/dossiers': typeof LocaleEspaceProDossiersRoute
  '/$locale/espace-pro/patients': typeof LocaleEspaceProPatientsRoute
  '/$locale/espace-pro/profil-public': typeof LocaleEspaceProProfilPublicRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/espace-patient/': typeof LocaleEspacePatientIndexRoute
  '/$locale/espace-pro/': typeof LocaleEspaceProIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/$locale/inscription': typeof LocaleInscriptionRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/login-admin': typeof LocaleLoginAdminRoute
  '/$locale/login-pro': typeof LocaleLoginProRoute
  '/$locale/mot-de-passe-oublie': typeof LocaleMotDePasseOublieRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/audit': typeof LocaleAdminAuditRoute
  '/$locale/admin/verifications': typeof LocaleAdminVerificationsRoute
  '/$locale/espace-patient/documents': typeof LocaleEspacePatientDocumentsRoute
  '/$locale/espace-patient/profil': typeof LocaleEspacePatientProfilRoute
  '/$locale/espace-patient/securite': typeof LocaleEspacePatientSecuriteRoute
  '/$locale/espace-pro/abonnement': typeof LocaleEspaceProAbonnementRoute
  '/$locale/espace-pro/dossiers': typeof LocaleEspaceProDossiersRoute
  '/$locale/espace-pro/patients': typeof LocaleEspaceProPatientsRoute
  '/$locale/espace-pro/profil-public': typeof LocaleEspaceProProfilPublicRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/$locale/admin': typeof LocaleAdminIndexRoute
  '/$locale/espace-patient': typeof LocaleEspacePatientIndexRoute
  '/$locale/espace-pro': typeof LocaleEspaceProIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/mcp': typeof McpRoute
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/espace-patient': typeof LocaleEspacePatientRouteWithChildren
  '/$locale/espace-pro': typeof LocaleEspaceProRouteWithChildren
  '/$locale/inscription': typeof LocaleInscriptionRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/login-admin': typeof LocaleLoginAdminRoute
  '/$locale/login-pro': typeof LocaleLoginProRoute
  '/$locale/mot-de-passe-oublie': typeof LocaleMotDePasseOublieRoute
  '/$locale/signup': typeof LocaleSignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/audit': typeof LocaleAdminAuditRoute
  '/$locale/admin/verifications': typeof LocaleAdminVerificationsRoute
  '/$locale/espace-patient/documents': typeof LocaleEspacePatientDocumentsRoute
  '/$locale/espace-patient/profil': typeof LocaleEspacePatientProfilRoute
  '/$locale/espace-patient/securite': typeof LocaleEspacePatientSecuriteRoute
  '/$locale/espace-pro/abonnement': typeof LocaleEspaceProAbonnementRoute
  '/$locale/espace-pro/dossiers': typeof LocaleEspaceProDossiersRoute
  '/$locale/espace-pro/patients': typeof LocaleEspaceProPatientsRoute
  '/$locale/espace-pro/profil-public': typeof LocaleEspaceProProfilPublicRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/espace-patient/': typeof LocaleEspacePatientIndexRoute
  '/$locale/espace-pro/': typeof LocaleEspaceProIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/mcp'
    | '/$locale/admin'
    | '/$locale/espace-patient'
    | '/$locale/espace-pro'
    | '/$locale/inscription'
    | '/$locale/login'
    | '/$locale/login-admin'
    | '/$locale/login-pro'
    | '/$locale/mot-de-passe-oublie'
    | '/$locale/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/$locale/'
    | '/$locale/admin/audit'
    | '/$locale/admin/verifications'
    | '/$locale/espace-patient/documents'
    | '/$locale/espace-patient/profil'
    | '/$locale/espace-patient/securite'
    | '/$locale/espace-pro/abonnement'
    | '/$locale/espace-pro/dossiers'
    | '/$locale/espace-pro/patients'
    | '/$locale/espace-pro/profil-public'
    | '/.mcp/invoke-tool/$tool'
    | '/$locale/admin/'
    | '/$locale/espace-patient/'
    | '/$locale/espace-pro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/$locale/inscription'
    | '/$locale/login'
    | '/$locale/login-admin'
    | '/$locale/login-pro'
    | '/$locale/mot-de-passe-oublie'
    | '/$locale/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/$locale'
    | '/$locale/admin/audit'
    | '/$locale/admin/verifications'
    | '/$locale/espace-patient/documents'
    | '/$locale/espace-patient/profil'
    | '/$locale/espace-patient/securite'
    | '/$locale/espace-pro/abonnement'
    | '/$locale/espace-pro/dossiers'
    | '/$locale/espace-pro/patients'
    | '/$locale/espace-pro/profil-public'
    | '/.mcp/invoke-tool/$tool'
    | '/$locale/admin'
    | '/$locale/espace-patient'
    | '/$locale/espace-pro'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/mcp'
    | '/$locale/admin'
    | '/$locale/espace-patient'
    | '/$locale/espace-pro'
    | '/$locale/inscription'
    | '/$locale/login'
    | '/$locale/login-admin'
    | '/$locale/login-pro'
    | '/$locale/mot-de-passe-oublie'
    | '/$locale/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/$locale/'
    | '/$locale/admin/audit'
    | '/$locale/admin/verifications'
    | '/$locale/espace-patient/documents'
    | '/$locale/espace-patient/profil'
    | '/$locale/espace-patient/securite'
    | '/$locale/espace-pro/abonnement'
    | '/$locale/espace-pro/dossiers'
    | '/$locale/espace-pro/patients'
    | '/$locale/espace-pro/profil-public'
    | '/.mcp/invoke-tool/$tool'
    | '/$locale/admin/'
    | '/$locale/espace-patient/'
    | '/$locale/espace-pro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/signup': {
      id: '/$locale/signup'
      path: '/signup'
      fullPath: '/$locale/signup'
      preLoaderRoute: typeof LocaleSignupRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/mot-de-passe-oublie': {
      id: '/$locale/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/$locale/mot-de-passe-oublie'
      preLoaderRoute: typeof LocaleMotDePasseOublieRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login-pro': {
      id: '/$locale/login-pro'
      path: '/login-pro'
      fullPath: '/$locale/login-pro'
      preLoaderRoute: typeof LocaleLoginProRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login-admin': {
      id: '/$locale/login-admin'
      path: '/login-admin'
      fullPath: '/$locale/login-admin'
      preLoaderRoute: typeof LocaleLoginAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/inscription': {
      id: '/$locale/inscription'
      path: '/inscription'
      fullPath: '/$locale/inscription'
      preLoaderRoute: typeof LocaleInscriptionRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/espace-pro': {
      id: '/$locale/espace-pro'
      path: '/espace-pro'
      fullPath: '/$locale/espace-pro'
      preLoaderRoute: typeof LocaleEspaceProRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/espace-patient': {
      id: '/$locale/espace-patient'
      path: '/espace-patient'
      fullPath: '/$locale/espace-patient'
      preLoaderRoute: typeof LocaleEspacePatientRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin': {
      id: '/$locale/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/espace-pro/': {
      id: '/$locale/espace-pro/'
      path: '/'
      fullPath: '/$locale/espace-pro/'
      preLoaderRoute: typeof LocaleEspaceProIndexRouteImport
      parentRoute: typeof LocaleEspaceProRoute
    }
    '/$locale/espace-patient/': {
      id: '/$locale/espace-patient/'
      path: '/'
      fullPath: '/$locale/espace-patient/'
      preLoaderRoute: typeof LocaleEspacePatientIndexRouteImport
      parentRoute: typeof LocaleEspacePatientRoute
    }
    '/$locale/admin/': {
      id: '/$locale/admin/'
      path: '/'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminIndexRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/espace-pro/profil-public': {
      id: '/$locale/espace-pro/profil-public'
      path: '/profil-public'
      fullPath: '/$locale/espace-pro/profil-public'
      preLoaderRoute: typeof LocaleEspaceProProfilPublicRouteImport
      parentRoute: typeof LocaleEspaceProRoute
    }
    '/$locale/espace-pro/patients': {
      id: '/$locale/espace-pro/patients'
      path: '/patients'
      fullPath: '/$locale/espace-pro/patients'
      preLoaderRoute: typeof LocaleEspaceProPatientsRouteImport
      parentRoute: typeof LocaleEspaceProRoute
    }
    '/$locale/espace-pro/dossiers': {
      id: '/$locale/espace-pro/dossiers'
      path: '/dossiers'
      fullPath: '/$locale/espace-pro/dossiers'
      preLoaderRoute: typeof LocaleEspaceProDossiersRouteImport
      parentRoute: typeof LocaleEspaceProRoute
    }
    '/$locale/espace-pro/abonnement': {
      id: '/$locale/espace-pro/abonnement'
      path: '/abonnement'
      fullPath: '/$locale/espace-pro/abonnement'
      preLoaderRoute: typeof LocaleEspaceProAbonnementRouteImport
      parentRoute: typeof LocaleEspaceProRoute
    }
    '/$locale/espace-patient/securite': {
      id: '/$locale/espace-patient/securite'
      path: '/securite'
      fullPath: '/$locale/espace-patient/securite'
      preLoaderRoute: typeof LocaleEspacePatientSecuriteRouteImport
      parentRoute: typeof LocaleEspacePatientRoute
    }
    '/$locale/espace-patient/profil': {
      id: '/$locale/espace-patient/profil'
      path: '/profil'
      fullPath: '/$locale/espace-patient/profil'
      preLoaderRoute: typeof LocaleEspacePatientProfilRouteImport
      parentRoute: typeof LocaleEspacePatientRoute
    }
    '/$locale/espace-patient/documents': {
      id: '/$locale/espace-patient/documents'
      path: '/documents'
      fullPath: '/$locale/espace-patient/documents'
      preLoaderRoute: typeof LocaleEspacePatientDocumentsRouteImport
      parentRoute: typeof LocaleEspacePatientRoute
    }
    '/$locale/admin/verifications': {
      id: '/$locale/admin/verifications'
      path: '/verifications'
      fullPath: '/$locale/admin/verifications'
      preLoaderRoute: typeof LocaleAdminVerificationsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/audit': {
      id: '/$locale/admin/audit'
      path: '/audit'
      fullPath: '/$locale/admin/audit'
      preLoaderRoute: typeof LocaleAdminAuditRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
  }
}

interface LocaleAdminRouteChildren {
  LocaleAdminAuditRoute: typeof LocaleAdminAuditRoute
  LocaleAdminVerificationsRoute: typeof LocaleAdminVerificationsRoute
  LocaleAdminIndexRoute: typeof LocaleAdminIndexRoute
}

const LocaleAdminRouteChildren: LocaleAdminRouteChildren = {
  LocaleAdminAuditRoute: LocaleAdminAuditRoute,
  LocaleAdminVerificationsRoute: LocaleAdminVerificationsRoute,
  LocaleAdminIndexRoute: LocaleAdminIndexRoute,
}

const LocaleAdminRouteWithChildren = LocaleAdminRoute._addFileChildren(
  LocaleAdminRouteChildren,
)

interface LocaleEspacePatientRouteChildren {
  LocaleEspacePatientDocumentsRoute: typeof LocaleEspacePatientDocumentsRoute
  LocaleEspacePatientProfilRoute: typeof LocaleEspacePatientProfilRoute
  LocaleEspacePatientSecuriteRoute: typeof LocaleEspacePatientSecuriteRoute
  LocaleEspacePatientIndexRoute: typeof LocaleEspacePatientIndexRoute
}

const LocaleEspacePatientRouteChildren: LocaleEspacePatientRouteChildren = {
  LocaleEspacePatientDocumentsRoute: LocaleEspacePatientDocumentsRoute,
  LocaleEspacePatientProfilRoute: LocaleEspacePatientProfilRoute,
  LocaleEspacePatientSecuriteRoute: LocaleEspacePatientSecuriteRoute,
  LocaleEspacePatientIndexRoute: LocaleEspacePatientIndexRoute,
}

const LocaleEspacePatientRouteWithChildren =
  LocaleEspacePatientRoute._addFileChildren(LocaleEspacePatientRouteChildren)

interface LocaleEspaceProRouteChildren {
  LocaleEspaceProAbonnementRoute: typeof LocaleEspaceProAbonnementRoute
  LocaleEspaceProDossiersRoute: typeof LocaleEspaceProDossiersRoute
  LocaleEspaceProPatientsRoute: typeof LocaleEspaceProPatientsRoute
  LocaleEspaceProProfilPublicRoute: typeof LocaleEspaceProProfilPublicRoute
  LocaleEspaceProIndexRoute: typeof LocaleEspaceProIndexRoute
}

const LocaleEspaceProRouteChildren: LocaleEspaceProRouteChildren = {
  LocaleEspaceProAbonnementRoute: LocaleEspaceProAbonnementRoute,
  LocaleEspaceProDossiersRoute: LocaleEspaceProDossiersRoute,
  LocaleEspaceProPatientsRoute: LocaleEspaceProPatientsRoute,
  LocaleEspaceProProfilPublicRoute: LocaleEspaceProProfilPublicRoute,
  LocaleEspaceProIndexRoute: LocaleEspaceProIndexRoute,
}

const LocaleEspaceProRouteWithChildren = LocaleEspaceProRoute._addFileChildren(
  LocaleEspaceProRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAdminRoute: typeof LocaleAdminRouteWithChildren
  LocaleEspacePatientRoute: typeof LocaleEspacePatientRouteWithChildren
  LocaleEspaceProRoute: typeof LocaleEspaceProRouteWithChildren
  LocaleInscriptionRoute: typeof LocaleInscriptionRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleLoginAdminRoute: typeof LocaleLoginAdminRoute
  LocaleLoginProRoute: typeof LocaleLoginProRoute
  LocaleMotDePasseOublieRoute: typeof LocaleMotDePasseOublieRoute
  LocaleSignupRoute: typeof LocaleSignupRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAdminRoute: LocaleAdminRouteWithChildren,
  LocaleEspacePatientRoute: LocaleEspacePatientRouteWithChildren,
  LocaleEspaceProRoute: LocaleEspaceProRouteWithChildren,
  LocaleInscriptionRoute: LocaleInscriptionRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleLoginAdminRoute: LocaleLoginAdminRoute,
  LocaleLoginProRoute: LocaleLoginProRoute,
  LocaleMotDePasseOublieRoute: LocaleMotDePasseOublieRoute,
  LocaleSignupRoute: LocaleSignupRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
