/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as PourQuiRouteImport } from './routes/pour-qui'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const PourQuiRoute = PourQuiRouteImport.update({
  id: '/pour-qui',
  path: '/pour-qui',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/inscription': typeof InscriptionRoute
  '/pour-qui': typeof PourQuiRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/inscription': typeof InscriptionRoute
  '/pour-qui': typeof PourQuiRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/inscription': typeof InscriptionRoute
  '/pour-qui': typeof PourQuiRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/fonctionnalites'
    | '/inscription'
    | '/pour-qui'
    | '/securite'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/fonctionnalites'
    | '/inscription'
    | '/pour-qui'
    | '/securite'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/fonctionnalites'
    | '/inscription'
    | '/pour-qui'
    | '/securite'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  InscriptionRoute: typeof InscriptionRoute
  PourQuiRoute: typeof PourQuiRoute
  SecuriteRoute: typeof SecuriteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour-qui': {
      id: '/pour-qui'
      path: '/pour-qui'
      fullPath: '/pour-qui'
      preLoaderRoute: typeof PourQuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  InscriptionRoute: InscriptionRoute,
  PourQuiRoute: PourQuiRoute,
  SecuriteRoute: SecuriteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
